//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimationSide
    {
        public int Id { get; set; }
        public string FirstRow_Background { get; set; }
        public string FirstRow_TopText { get; set; }
        public string FirstRow_MiddleText { get; set; }
        public string FirstRow_BottomText { get; set; }
        public string SecondRow_Background { get; set; }
        public string SecondRow_TopText { get; set; }
        public string SecondRow_MiddleText { get; set; }
        public string SecondRow_Button { get; set; }
        public string SecondRow_TopTextSpan { get; set; }
    }
}
