//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipping
    {
        public int Id { get; set; }
        public string Shipping_Company { get; set; }
        public string Shipping_Cost { get; set; }
        public string Delivery_Time { get; set; }
        public Nullable<bool> Tracking_Information { get; set; }
    }
}
