//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animation
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Top_Text { get; set; }
        public string Middle_Text { get; set; }
        public string Bottom_Text { get; set; }
        public string Price { get; set; }
    }
}
