//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public string Image { get; set; }
        public Nullable<byte> Rating { get; set; }
        public Nullable<int> Review_Count { get; set; }
        public Nullable<byte> Discount { get; set; }
        public Nullable<bool> New { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Brand_Id { get; set; }
        public Nullable<int> Color_Id { get; set; }
        public Nullable<int> Size_Id { get; set; }
        public Nullable<bool> Featured { get; set; }
        public Nullable<bool> Special { get; set; }
        public Nullable<bool> Onsale { get; set; }
        public Nullable<bool> Top_Selling_Week { get; set; }
        public string Details_1 { get; set; }
        public string Details_2 { get; set; }
        public string Details_3 { get; set; }
        public string Details_4 { get; set; }
        public string Details_5 { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Category Category { get; set; }
        public virtual Color Color { get; set; }
        public virtual Size Size { get; set; }
    }
}
